services:
  fitrations:
    build: .
    image: ghcr.io/xvipesx/fitrations:latest
    environment:
      - DB_PATH=/app/data/fitrations.db
    ports:
      - "80:80"
    volumes:
      - ./data:/app/data
    restart: unless-stopped