services:
  fitrations:
    image: ghcr.io/xvipesx/fitrations:0.1.0
    environment:
      - DB_PATH=/app/data/fitrations.db
      - BACKUP_DIR=/app/data/backups
      - TIME_ZONE=America/New_York
      # Seperate allowed origins by comma
      - ALLOWED_ORIGINS=http://yourdomain.com,http://your-server-ip:8080
    ports:
      - "8080:80"
    volumes:
      - ./data:/app/data
    restart: unless-stopped